### ISSUE TITLE
Timeout::Error: Timeout while waiting for password agent to perform password reset

### ISSUE THREAD

**Issue by lmayorga1980** [test-kitchen/kitchen-google#117]
## :speaking_head: Foreword

`kitchen-google` fails when using Windows over SSH.

## :ghost: Brief Description

I am trying to run test-kitchen with gcp but get an error of timing out when trying to reset the password. When using Windows over SSH the password is not really needed.

## Version

```
kitchen-google (2.3.0)
kitchen-inspec (2.6.1)
```

## Environment

OSX Monterrey

## Scenario

```yaml
---
driver:
  name: gce
  project: my-project
  zone: us-east4-b
  service_account_name: my_svc_account
  email: <IS THIS REALLY NEEDED ON WINDOWS OVER-SSH>
  network_project: shared_project
  network: shared_vpc
  subnet_project: shared_subnet
  subnet: subnet_id
  use_private_ip: true
  machine_type: n1-standard-16
  preemptible: true
  tags:
    - test-kitchen

provisioner:
  name: shell
  command: 'hostname'        

verifier:
  name: inspec

transport:
  username: my_local_admin
  ssh_key:
    - ~/.ssh/id_kitchen_gcp
platforms:
  - name: windows
    driver:
      image_project: shared-image-project
      image_family: image-family
      disk_size: 60
      metadata:
        application: windows
        windows-startup-script-cmd: echo <%= ENV['KITCHEN_GCP_PUB_KEY']%> > C:\\ProgramData\\ssh\\administrators_authorized_keys
```
```
-----> Creating <default-windows>...
$$$$$$ These configs are deprecated - consider using new disks configuration
       Creating GCE instance <tk-default-windows-c1c8f9> in project my-project, zone us-east4-b...
       Creating a 60 GB boot disk named tk-default-windows-c1c8f9-disk1 from image my-image...
       Current status: RUNNING
       Current status: DONE
       Server <tk-default-windows-c1c8f9> created.
       Resetting the Windows password for user my_local_admin on tk-default-windows-c1c8f9...
>>>>>> Error encountered during server creation: Timeout::Error: Timeout while waiting for password agent to perform password reset
       Destroying GCE instance <tk-default-windows-c1c8f9>...
       Current status: RUNNING
       Current status: DONE
       GCE instance <tk-default-windows-c1c8f9> destroyed
```
