### ISSUE TITLE
Driver not in load path in latest chefdk

### ISSUE THREAD

**Issue by devoptimist** [test-kitchen/kitchen-google#50]
Apologies if I am missing something basic, but this driver appears to be broken when used with the latest chefdk.
I started from a clean install and was following the instructions on Chef Rally https://learn.chef.io/modules/local-development/rhel/gcp/apply-a-cookbook#/. 

chefdk version: chefdk-2.0.28-1.el7.x86_64
OS: Fedora 26

I performed a 'chef gem install kitchen-google'

then ran kitchen list
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'gce' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

kitchen diagnose --all
```
  error:
    exception: "#<Kitchen::ClientError: Could not load the 'gce' driver from the load
      path. Please ensure that your driver is installed as a gem or included in your
      Gemfile if using Bundler.>"
    message: Could not load the 'gce' driver from the load path. Please ensure that
      your driver is installed as a gem or included in your Gemfile if using Bundler.
    backtrace:
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/driver.rb:52:in
      `rescue in for_plugin'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/driver.rb:38:in
      `for_plugin'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:233:in
      `new_driver'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:246:in
      `new_instance'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:142:in
      `block in build_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in
      `map'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in
      `with_index'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in
      `build_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:117:in
      `instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:112:in
      `filtered_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:142:in
      `parse_subcommand'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:53:in
      `load_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:32:in
      `block in call'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:73:in
      `record_failure'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:32:in
      `call'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in
      `perform'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:143:in
      `diagnose'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in
      `invoke_task'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in
      `dispatch'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
      `start'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in
      `block in <top (required)>'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in
      `with_friendly_errors'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in
      `<top (required)>'"
    - "/usr/bin/kitchen:263:in `load'"
    - "/usr/bin/kitchen:263:in `<main>'"
```

kitchen.yml
```
---
driver:
  name: gce
  project: project-1
  zone: europe-west1
  email: myemail@mail.com
  tags:
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: myuser

platforms:
  - name: centos-7.2
    driver:
      image_project: centos-cloud
      image_name: centos-7-v20170227

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```

Gemfile
```
source 'https://rubygems.org'

gem 'berkshelf'

group :integration do
  gem "kitchen-google", "~> 1.0"
end
```
If I installed kitchen-gce I could get kitchen to work. It is somewhat confusing that bot these gems use the driver name gce. From what I have read kitchen-google is the official driver. So could you help me understand why it is not in the load path after installing the kitchen-google gem?
