### ISSUE TITLE
can't get disk configuration to work

### ISSUE THREAD

**Issue by Zhann** [test-kitchen/kitchen-google#67]
My kitchen file:

```yml
---
driver:
  name: gce
  project: foo-bar-946f7c97
  zone: europe-west1-b
  tags:
    - ops
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email

transport:
  username: <%= ENV['USER'] %>
  ssh_key: <%= ENV['SSH_KEY'] %>

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image_project: ubuntu-os-cloud
      image_name: ubuntu-1404-trusty-v20181004
      disks:
        disk0:
          autodelete_disk: true
        disk1:
          disk_size: 10

suites:
  - name: default
    run_list:
      - recipe[sf_postgres::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

Where I've put `disks` under driver. It converges the node, but there's no extra disk attached:

```
steven@tk-default-ubuntu-1404-d5b510:~$ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  10G  0 disk
`-sda1   8:1    0  10G  0 part /
steven@tk-default-ubuntu-1404-d5b510:~$
```

I've tried putting the `disks` configuration at the top driver section, but no luck there either. What am I doing wrong?
