### ISSUE TITLE
WinRM doesn't work on GCP Windows 2016 Images

### ISSUE THREAD

**Issue by stonest** [test-kitchen/kitchen-google#68]
When trying to connect through WinRM it will eventually time out with:

```
-----> Starting Kitchen (v1.23.2)
D      Berksfile found at /Users/Stuart/nwm/domain_join/Berksfile, loading Berkshelf
D      Berkshelf 7.0.6 library loaded
D      winrm requested, loading winrm gem (["~> 2.0"])
D      winrm is loaded.
D      winrm-fs requested, loading winrm-fs gem (["~> 1.0"])
D      winrm-fs is loaded.
-----> Creating <default-windows>...
Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
$$$$$$ No bootdisk found - Assuming first disk will be boot disk
       Creating GCE instance <tk-default-windows-823cfa> in project cr-lab-sstone-2210184342, zone europe-west2-a...
       Creating a 100 GB boot disk named tk-default-windows-823cfa-disk0...
       Current status: PENDING
       Current status: RUNNING
       Current status: DONE
       Server <tk-default-windows-823cfa> created.
       Resetting the Windows password for user administrator on tk-default-windows-823cfa...
Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
       Password reset complete on tk-default-windows-823cfa complete.
       Waiting for server <tk-default-windows-823cfa> to be ready...
D      [WinRM] <{:endpoint=>"http://XXXXXXX:5985/wsman", :user=>"administrator", :password=>"XXXXXX", :transport=>:negotiate, :elevated_username=>"administrator", :elevated_password=>"XXXXXXX", :no_ssl_peer_verification=>true, :disable_sspi=>false, :basic_auth_only=>false}> (Write-Host '[WinRM] Established
')
D      [WinRM] opening remote shell on http://XXXXXXX:5985/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
```

gem versions:
kitchen-google (2.0.0)
winrm (2.3.0)
winrm-elevated (1.1.0)
winrm-fs (1.3.1)

kitchen version v1.23.2

**Comment by stonest** [comment]
So the actual problem here was that in GCP Windows images the administrator account is disabled by default, however there doesn't seem to be any check in whether or not you are specifying this username.

**Comment by wilhelmi** [comment]
What was the fix to enable this for test-kitchen?

**Comment by stonest** [comment]
From memory, the fix was to specify a username that was not administrator in the transport settings, this allowed it to run properly

**Comment by wilhelmi** [comment]
Thanks for the quick response. Here is where I am stuck:

This is my current test-kitchen config:

```yaml
transport:
  name: winrm
  elevated: true
  username: test-kitchen
  password: Pass@word1
  winrm_transport: plaintext

platforms:
  - name: windows-server-2016-dc
    driver:
      image_project: windows-cloud
      image_name: windows-server-2016-dc-v20190514 
      subnet: test-kitchen
      username: test-kitchen
      password: Pass@word1
      metadata: 
        windows-startup-script-cmd: "winrm quickconfig -quiet & winrm set winrm/config/winrs '@{MaxMemoryPerShellMB=\"512\"}' & winrm set winrm/config '@{MaxTimeoutms=\"1800000\"}' & winrm set winrm/config/service '@{AllowUnencrypted=\"true\"}' & winrm set winrm/config/service/auth @{Basic=\"true\" & winrm set winrm/config/client/auth '@{Basic=\"true\"}'}"
```
This times out with the error you note:

```bash
       Password reset complete on tk-default-windows-server-2016-dc-c2c395 complete.
       Waiting for server <tk-default-windows-server-2016-dc-c2c395> to be ready...
D      [WinRM] <{:endpoint=>"http://***:5985/wsman", :user=>"test-kitchen", :password=>"!~&y%i&|JE:fB-v", :transport=>:plaintext, :elevated_username=>"test-kitchen", :elevated_password=>"!~&y%i&|JE:fB-v", :disable_sspi=>true, :basic_auth_only=>true}> (Write-Host '[WinRM] Established
')
D      [WinRM] opening remote shell on http://****:5985/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
```
What has me stumped is I have a packer build using the same source image and windows-startup-script-cmd script, it works.

**Comment by stonest** [comment]
can you take the password field out of your test kitchen config? that might have something to do with it

**Comment by wilhelmi** [comment]
Removing that field didn't make a difference.

**Comment by stonest** [comment]
from both transport and platforms?

**Comment by wilhelmi** [comment]
correct:

```yaml
transport:
  name: winrm
  elevated: true
  username: test-kitchen
  winrm_transport: plaintext

platforms:
  - name: windows-server-2016-dc
    driver:
      image_project: windows-cloud
      image_name: windows-server-2016-dc-v20190514 
      subnet: test-kitchen
      username: test-kitchen
      metadata: 
        windows-startup-script-cmd: "net user /add test-kitchen & net localgroup administrators test-kitchen /add & winrm quickconfig -quiet & winrm set winrm/config/winrs '@{MaxMemoryPerShellMB=\"512\"}' & winrm set winrm/config '@{MaxTimeoutms=\"1800000\"}' & winrm set winrm/config/service '@{AllowUnencrypted=\"true\"}' & winrm set winrm/config/service/auth @{Basic=\"true\" & winrm set winrm/config/client/auth '@{Basic=\"true\"}'}"
```

```bash
D      [WinRM] opening remote shell on http://***:5985/wsman
D      [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [WinRM::WinRMAuthorizationError] on default-windows-server-2016-dc
D      ----------------------

```
